2022-08-09 20:35:31.648780: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-08-09 20:35:31.648816: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "/home/mgatlin3/FT/2dCNN.py", line 4, in <module>
    from keras.layers import Conv2D, MaxPooling2D, GlobalAveragePooling2D, Flatten
  File "/home/mgatlin3/.local/lib/python3.9/site-packages/keras/__init__.py", line 21, in <module>
    from tensorflow.python import tf2
  File "/home/mgatlin3/.local/lib/python3.9/site-packages/tensorflow/__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/home/mgatlin3/.local/lib/python3.9/site-packages/tensorflow/python/__init__.py", line 42, in <module>
    from tensorflow.python import data
  File "/home/mgatlin3/.local/lib/python3.9/site-packages/tensorflow/python/data/__init__.py", line 21, in <module>
    from tensorflow.python.data import experimental
  File "/home/mgatlin3/.local/lib/python3.9/site-packages/tensorflow/python/data/experimental/__init__.py", line 95, in <module>
    from tensorflow.python.data.experimental import service
  File "/home/mgatlin3/.local/lib/python3.9/site-packages/tensorflow/python/data/experimental/service/__init__.py", line 387, in <module>
    from tensorflow.python.data.experimental.ops.data_service_ops import distribute
  File "/home/mgatlin3/.local/lib/python3.9/site-packages/tensorflow/python/data/experimental/ops/data_service_ops.py", line 25, in <module>
    from tensorflow.python.data.ops import dataset_ops
  File "/home/mgatlin3/.local/lib/python3.9/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 31, in <module>
    from tensorflow.python.data.ops import iterator_ops
  File "/home/mgatlin3/.local/lib/python3.9/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 35, in <module>
    from tensorflow.python.training.saver import BaseSaverBuilder
  File "/home/mgatlin3/.local/lib/python3.9/site-packages/tensorflow/python/training/saver.py", line 37, in <module>
    from tensorflow.python.framework import meta_graph
  File "/home/mgatlin3/.local/lib/python3.9/site-packages/tensorflow/python/framework/meta_graph.py", line 18, in <module>
    from packaging import version as packaging_version  # pylint: disable=g-bad-import-order
ModuleNotFoundError: No module named 'packaging'
