2022-08-30 15:38:53,452 INFO    Thread-5280:116206 [wandb_setup.py:_flush():75] Loading settings from /home/mgatlin3/.config/wandb/settings
2022-08-30 15:38:53,452 INFO    Thread-5280:116206 [wandb_setup.py:_flush():75] Loading settings from wandb/settings
2022-08-30 15:38:53,452 INFO    Thread-5280:116206 [wandb_setup.py:_flush():75] Loading settings from environment variables: {'project': 'sweep-FT', 'entity': 'mgatlin3', 'root_dir': '/home/mgatlin3/FT', 'run_id': 'k6gna86l', 'sweep_param_path': '/home/mgatlin3/FT/wandb/sweep-paq5irxm/config-k6gna86l.yaml', 'sweep_id': 'paq5irxm'}
2022-08-30 15:38:53,452 INFO    Thread-5280:116206 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program_relpath': 'sweep.py', 'program': '/home/mgatlin3/FT/sweep.py'}
2022-08-30 15:38:53,453 INFO    Thread-5280:116206 [wandb_init.py:_log_setup():437] Logging user logs to /home/mgatlin3/FT/wandb/run-20220830_153853-k6gna86l/logs/debug.log
2022-08-30 15:38:53,453 INFO    Thread-5280:116206 [wandb_init.py:_log_setup():438] Logging internal logs to /home/mgatlin3/FT/wandb/run-20220830_153853-k6gna86l/logs/debug-internal.log
2022-08-30 15:38:53,453 INFO    Thread-5280:116206 [wandb_init.py:init():471] calling init triggers
2022-08-30 15:38:53,453 INFO    Thread-5280:116206 [wandb_init.py:init():474] wandb.init called with sweep_config: {'batch_size': 2, 'dropout_c': 0.1, 'dropout_ga': 0.4, 'epochs': 80, 'learning_rate': 0.00075, 'num_features_c1': 16, 'num_features_c2': 64, 'num_features_c3': 64, 'num_features_c4': 128}
config: {'batch_size': 4, 'epochs': 5, 'dropout_c': 0.3, 'dropout_ga': 0.1, 'num_features_c1': 64, 'num_features_c2': 64, 'num_features_c3': 128, 'num_features_c4': 64, 'learning_rate': 0.0003}
2022-08-30 15:38:53,453 INFO    Thread-5280:116206 [wandb_init.py:init():524] starting backend
2022-08-30 15:38:53,453 INFO    Thread-5280:116206 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-08-30 15:38:53,457 INFO    Thread-5280:116206 [backend.py:ensure_launched():217] starting backend process...
2022-08-30 15:38:53,563 INFO    Thread-5280:116206 [backend.py:ensure_launched():222] started backend process with pid: 54311
2022-08-30 15:38:53,564 INFO    Thread-5280:116206 [wandb_init.py:init():533] backend started and connected
2022-08-30 15:38:53,572 INFO    Thread-5280:116206 [wandb_run.py:_config_callback():1131] config_cb None None {'batch_size': 2, 'dropout_c': 0.1, 'dropout_ga': 0.4, 'epochs': 80, 'learning_rate': 0.00075, 'num_features_c1': 16, 'num_features_c2': 64, 'num_features_c3': 64, 'num_features_c4': 128}
2022-08-30 15:38:53,577 INFO    Thread-5280:116206 [wandb_init.py:init():597] updated telemetry
2022-08-30 15:38:53,827 INFO    Thread-5280:116206 [wandb_init.py:init():628] communicating run to backend with 30 second timeout
2022-08-30 15:38:54,541 INFO    Thread-5280:116206 [wandb_run.py:_on_init():1923] communicating current version
2022-08-30 15:38:54,642 INFO    Thread-5280:116206 [wandb_run.py:_on_init():1927] got version response upgrade_message: "wandb version 0.13.2 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-08-30 15:38:54,642 INFO    Thread-5280:116206 [wandb_init.py:init():659] starting run threads in backend
2022-08-30 15:38:59,122 INFO    Thread-5280:116206 [wandb_run.py:_console_start():1897] atexit reg
2022-08-30 15:38:59,122 INFO    Thread-5280:116206 [wandb_run.py:_redirect():1770] redirect: SettingsConsole.REDIRECT
2022-08-30 15:38:59,122 INFO    Thread-5280:116206 [wandb_run.py:_redirect():1775] Redirecting console.
2022-08-30 15:38:59,123 ERROR   Thread-5280:116206 [wandb_run.py:_redirect():1834] Failed to redirect.
Traceback (most recent call last):
  File "/home/mgatlin3/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1827, in _redirect
    out_redir.install()
  File "/home/mgatlin3/.local/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 709, in install
    _WSCH.add_fd(self._pipe_read_fd)
  File "/home/mgatlin3/.local/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in add_fd
    self._register()
  File "/home/mgatlin3/.local/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 644, in _register
    old_handler = signal.signal(signal.SIGWINCH, lambda *_: None)
  File "/home/mgatlin3/.conda/envs/poop/lib/python3.9/signal.py", line 56, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread of the main interpreter
2022-08-30 15:38:59,123 INFO    Thread-5280:116206 [wandb_init.py:init():684] run started, returning control to user process
2022-08-30 15:38:59,123 INFO    Thread-5280:116206 [wandb_config.py:__setitem__():150] config set architecture_name = CNN - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x7ffac378afa0>>
2022-08-30 15:38:59,123 INFO    Thread-5280:116206 [wandb_run.py:_config_callback():1131] config_cb architecture_name CNN None
2022-08-30 17:29:28,252 ERROR   Thread-1  :116206 [internal_api.py:execute():143] 500 response executing GraphQL.
2022-08-30 17:29:28,254 ERROR   Thread-1  :116206 [internal_api.py:execute():144] {"errors":[{"message":"context deadline exceeded"}]}
2022-08-30 17:30:06,806 ERROR   Thread-1  :116206 [internal_api.py:execute():143] 500 response executing GraphQL.
2022-08-30 17:30:06,807 ERROR   Thread-1  :116206 [internal_api.py:execute():144] {"errors":[{"message":"internal database error","path":["agentHeartbeat"]}],"data":{"agentHeartbeat":null}}
2022-08-30 17:30:13,635 ERROR   Thread-1  :116206 [internal_api.py:execute():143] 500 response executing GraphQL.
2022-08-30 17:30:13,636 ERROR   Thread-1  :116206 [internal_api.py:execute():144] {"errors":[{"message":"internal database error","path":["agentHeartbeat"]}],"data":{"agentHeartbeat":null}}
2022-08-30 17:30:13,636 ERROR   Thread-1  :116206 [retry.py:__call__():126] Retry attempt failed:
Traceback (most recent call last):
  File "/home/mgatlin3/.local/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/mgatlin3/.local/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 140, in execute
    return self.client.execute(*args, **kwargs)
  File "/home/mgatlin3/.local/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/mgatlin3/.local/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/mgatlin3/.local/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/transport/requests.py", line 39, in execute
    request.raise_for_status()
  File "/home/mgatlin3/.conda/envs/poop/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://api.wandb.ai/graphql
2022-08-30 17:30:17,931 ERROR   Thread-1  :116206 [internal_api.py:execute():143] 500 response executing GraphQL.
2022-08-30 17:30:17,931 ERROR   Thread-1  :116206 [internal_api.py:execute():144] {"error":"internal database error"}
2022-08-30 17:30:28,220 ERROR   Thread-1  :116206 [internal_api.py:execute():143] 500 response executing GraphQL.
2022-08-30 17:30:28,221 ERROR   Thread-1  :116206 [internal_api.py:execute():144] {"error":"internal database error"}
2022-08-30 17:30:46,842 ERROR   Thread-1  :116206 [internal_api.py:execute():143] 500 response executing GraphQL.
2022-08-30 17:30:46,843 ERROR   Thread-1  :116206 [internal_api.py:execute():144] {"error":"internal database error"}
2022-08-30 17:31:21,926 ERROR   Thread-1  :116206 [internal_api.py:execute():143] 500 response executing GraphQL.
2022-08-30 17:31:21,926 ERROR   Thread-1  :116206 [internal_api.py:execute():144] {"error":"internal database error"}
2022-08-30 19:15:05,577 INFO    Thread-5280:116206 [wandb_run.py:_finish():1685] finishing run mgatlin3/sweep-FT/k6gna86l
2022-08-30 19:15:05,577 INFO    Thread-5280:116206 [wandb_run.py:_atexit_cleanup():1866] got exitcode: 0
2022-08-30 19:15:05,585 INFO    Thread-5280:116206 [wandb_run.py:_restore():1838] restore
2022-08-30 19:15:05,589 INFO    Thread-5280:116206 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 1
  media_count: 1
  other_count: 1
}
pusher_stats {
  uploaded_bytes: 1514867
  total_bytes: 1514867
}

2022-08-30 19:15:05,741 INFO    Thread-5280:116206 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 1
  media_count: 1
  other_count: 1
}
pusher_stats {
  uploaded_bytes: 1514867
  total_bytes: 1514867
}

2022-08-30 19:15:06,106 INFO    Thread-5280:116206 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 1
  media_count: 1
  other_count: 1
}
pusher_stats {
  uploaded_bytes: 1514867
  total_bytes: 1514867
}

2022-08-30 19:15:06,208 INFO    Thread-5280:116206 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 5
  media_count: 1
  other_count: 1
}
pusher_stats {
  uploaded_bytes: 3379
  total_bytes: 1524700
}

2022-08-30 19:15:06,310 INFO    Thread-5280:116206 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 5
  media_count: 1
  other_count: 1
}
pusher_stats {
  uploaded_bytes: 799644
  total_bytes: 1524700
}

2022-08-30 19:15:06,411 INFO    Thread-5280:116206 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 5
  media_count: 1
  other_count: 1
}
pusher_stats {
  uploaded_bytes: 1524700
  total_bytes: 1524700
}

2022-08-30 19:15:06,514 INFO    Thread-5280:116206 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 5
  media_count: 1
  other_count: 1
}
pusher_stats {
  uploaded_bytes: 1524700
  total_bytes: 1524700
}

2022-08-30 19:15:06,616 INFO    Thread-5280:116206 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 5
  media_count: 1
  other_count: 1
}
pusher_stats {
  uploaded_bytes: 1524700
  total_bytes: 1524700
}

2022-08-30 19:15:06,718 INFO    Thread-5280:116206 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 5
  media_count: 1
  other_count: 1
}
pusher_stats {
  uploaded_bytes: 1524700
  total_bytes: 1524700
}

2022-08-30 19:15:06,820 INFO    Thread-5280:116206 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 5
  media_count: 1
  other_count: 1
}
pusher_stats {
  uploaded_bytes: 1524700
  total_bytes: 1524700
}

2022-08-30 19:15:06,998 INFO    Thread-5280:116206 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 5
  media_count: 1
  other_count: 1
}
pusher_stats {
  uploaded_bytes: 1524700
  total_bytes: 1524700
}

2022-08-30 19:15:07,199 INFO    Thread-5280:116206 [wandb_run.py:_on_finish():1995] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
  media_count: 1
  other_count: 1
}
pusher_stats {
  uploaded_bytes: 1524700
  total_bytes: 1524700
}
local_info {
}

2022-08-30 19:15:08,734 INFO    Thread-5280:116206 [wandb_run.py:_footer_history_summary_info():3102] rendering history
2022-08-30 19:15:08,735 INFO    Thread-5280:116206 [wandb_run.py:_footer_history_summary_info():3134] rendering summary
2022-08-30 19:15:08,739 INFO    Thread-5280:116206 [wandb_run.py:_footer_sync_info():3057] logging synced files
